name: Python code quality and tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

env:
  DEFAULT_PYTHON: "3.12"
  PROJECT_PATH: "bumper"

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: "actions/checkout@v4"

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]
      # Following steps cannot run by pre-commit.ci as repo = local
      - name: Run mypy
        run: mypy ${{ env.PROJECT_PATH }}/
      - name: Pylint review
        run: pylint ${{ env.PROJECT_PATH }}/

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: "actions/checkout@v4"

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]
      - name: Run pytest
        run: pytest --cov=./ --cov-report=xml

      # https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
